export interface TranscriptEntry {
  speaker: "customer" | "agent";
  text: string;
  timestamp: Date;
}

export interface ActionItem {
  id: string;
  action: string;
  owner:
    | "isr"
    | "customer"
    | "branch_manager"
    | "dispatch"
    | "field_service"
    | "billing"
    | "national_accounts"
    | string;
  priority: "critical" | "high" | "medium" | "low";
  deadline: string;
  status: "pending" | "in_progress" | "completed";
  notes?: string;
}

export interface NextStep {
  step: string;
  owner?: string;
  timeline?: string;
  channel?: "phone" | "email" | "rentalman_update" | "total_control" | "in_person";
}

/** Equipment requested as returned by summary agent */
export interface EquipmentRequested {
  equipment_type?: string;
  location_preferred?: string;
  rental_start_date?: string;
  requested_duration_days?: number;
  delivery_request?: {
    requested_delivery_date?: string;
    requested_delivery_before?: string;
  };
}

/** Call categories from summary agent */
export interface CallCategories {
  primary_type?: string;
  secondary_types?: string[];
}

/** Sentiment from summary agent */
export interface SentimentSummary {
  customer_sentiment?: string;
  summary?: string;
  score_1_to_5?: number;
}

/** Retention risk from summary agent */
export interface RetentionRiskSummary {
  risk_level?: string;
  rationale?: string;
}

/** Customer update applied by summary agent */
export interface CustomerUpdateSummary {
  update_applied?: boolean;
  updated_fields?: Record<string, unknown>;
  updated_by?: string;
  updated_at?: string;
}

/** Record management / storage from summary agent */
export interface RecordManagement {
  record_saved?: boolean;
  storage_location?: string;
  saved_by?: string;
  saved_at?: string;
}

/** Equipment issue from summary agent (alternate response shape) */
export interface EquipmentIssue {
  equipment_type?: string;
  symptoms?: string[];
  visible_damage?: string[];
}

export interface EquipmentDiscussed {
  type: string;
  model?: string;
  details: string;
  action_needed?: string;
  certification_required?: string | null;
}

export interface CustomerHealth {
  sentiment:
    | "satisfied"
    | "neutral"
    | "concerned"
    | "frustrated"
    | "angry"
    | "at_risk";
  sentiment_triggers: string[];
  retention_risk: "none" | "low" | "medium" | "high";
  retention_risk_reason?: string;
  expansion_opportunity?: string | null;
  nps_estimate?: string;
}

export interface BillingDetails {
  charges_discussed: string[];
  dispute_amount?: string | null;
  resolution?: string;
}

export interface CallSummaryMeta {
  call_id: string;
  call_date: string;
  call_duration_estimate: string;
  call_category: string;
  subcategory?: string;
  customer_name: string;
  customer_account?: string | null;
  customer_phone?: string | null;
  customer_email?: string | null;
  isr_name?: string | null;
  branch?: string | null;
  contract_number?: string | null;
  /** Demo-only fields: spoofed persona and intent from Co-pilot */
  spoof_persona?: string;
  spoof_intent?: string;
}

export interface CallRecord {
  call_summary: CallSummaryMeta;
  summary: string;
  key_topics: string[];
  equipment_discussed: EquipmentDiscussed[];
  action_items: ActionItem[];
  next_steps: NextStep[];
  customer_health: CustomerHealth;
  billing_details?: BillingDetails;
  customer_record_update?: {
    should_update: boolean;
    fields_to_update: Record<string, unknown>;
  };
  follow_up_required: boolean;
  follow_up_details?: string;
  internal_notes?: string;
  transcript?: TranscriptEntry[];
  /** Full summary agent output fields */
  account_id?: string;
  account_name?: string;
  call_date?: string;
  equipment_requested?: EquipmentRequested;
  call_categories?: CallCategories;
  sentiment?: SentimentSummary;
  retention_risk?: RetentionRiskSummary;
  customer_update?: CustomerUpdateSummary;
  stored_transcript?: string;
  record_management?: RecordManagement;
  job_site?: string;
  equipment_issue?: EquipmentIssue;
  /** True when summary was generated by local fallback (Lyzr failed). Not persisted to DB. */
  _usedLocalFallback?: boolean;
}

export interface ResolutionStep {
  step: number;
  action: string;
  detail: string;
  system_reference?: string | null;
}

export interface ResolutionSuggestion {
  off_topic: boolean;
  message?: string;
  intent_detected?: string;
  confidence?: number;
  customer_sentiment?: string;
  sentiment_cues?: string;
  whisper_response?: string;
  suggested_response?: string;
  de_escalation_tip?: string | null;
  resolution_steps?: ResolutionStep[];
  knowledge_references?: { title: string; relevant_excerpt: string }[];
  equipment_info?: {
    mentioned: string[];
    specs_available: boolean;
    certification_required?: string | null;
    accessories_to_suggest?: string[];
  };
  escalation?: {
    needed: boolean;
    reason?: string;
    escalate_to?: string | null;
  };
  cross_sell_opportunity?: string | null;
  next_best_action?: string;
}

export interface CustomerRecord {
  account_id: string;
  customer_name: string;
  email: string;
  phone: string;
  branch: string;
  account_type: "national" | "local" | "walk_in";
  account_status: "active" | "on_hold" | "cod_only" | "inactive";
  credit_limit: number;
  total_rentals: number;
  last_contact_date: string;
  last_contact_reason: string;
  notes: string[];
  active_rentals: {
    contract_number: string;
    equipment: string;
    start_date: string;
    jobsite: string;
  }[];
  jobsites: string[];
}

export interface CustomerRecordUpdate {
  account_id: string;
  last_contact_date?: string;
  last_contact_reason?: string;
  last_contact_summary?: string;
  notes_to_add?: string;
  equipment_of_interest?: string[];
  status_change?: string;
  new_jobsite?: string;
  call_id?: string;
  follow_up_date?: string;
}
